"""add_is_estimated_and_data_source

Revision ID: a57ab300b4a7
Revises: 0001_initial_schema
Create Date: 2026-09-12 14:50:53.454011

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a57ab300b4a7'
down_revision: str | None = '0001_initial_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_data', sa.Column('is_estimated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('activity_data', sa.Column('data_source', sa.String(length=50), server_default='measured', nullable=False))
    op.add_column('baseline_results', sa.Column('is_estimated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('baseline_results', sa.Column('data_source', sa.String(length=50), server_default='measured', nullable=False))
    op.add_column('hotspots', sa.Column('is_estimated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('hotspots', sa.Column('data_source', sa.String(length=50), server_default='measured', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspots', 'data_source')
    op.drop_column('hotspots', 'is_estimated')
    op.drop_column('baseline_results', 'data_source')
    op.drop_column('baseline_results', 'is_estimated')
    op.drop_column('activity_data', 'data_source')
    op.drop_column('activity_data', 'is_estimated')
    # ### end Alembic commands ###
